### ISSUE TITLE
Add "Animals Under Observation" Screen

### ISSUE THREAD

**Issue by andrewtran1995** [Kaikat/ATlatoque#6]
One page per animal that lists all animals "under observation," i.e., that it is being nursed. An animals is being nursed if it has been caught but not yet released.

Owned refers to caught or released.

**Comment by andrewtran1995** [comment]
@Kaikat, to double check, this screen is supposed to come from the IDCardObject screen, correct?

**Comment by Kaikat** [comment]
Yes if you click on a specific animal that you already own or have previously owned you should be able to see the list of all the ones of that type. I shared a google drive image with you both just now.
